spring.application.name=realtimeorders
spring.datasource.url=jdbc:mysql://localhost:3306/realtime_orders

spring.datasource.username=root

spring.datasource.password=shraVani2712

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080
